In [2]:
import pandas as pd

df_final = pd.read_csv(r"C:/Users/PC/DATA/final/dataset_final.csv", sep=",")

In [3]:
def atmo_pm25(x):
    if x <= 10: return 1
    elif x <= 20: return 2
    elif x <= 25: return 3
    elif x <= 50: return 4
    elif x <= 75: return 5
    else: return 6

def atmo_pm10(x):
    if x <= 20: return 1
    elif x <= 40: return 2
    elif x <= 50: return 3
    elif x <= 100: return 4
    elif x <= 150: return 5
    else: return 6

def atmo_no2(x):
    if x <= 40: return 1
    elif x <= 90: return 2
    elif x <= 120: return 3
    elif x <= 230: return 4
    elif x <= 340: return 5
    else: return 6

In [4]:
df_final["atmo_pm25"] = df_final["PM2.5"].apply(atmo_pm25)
df_final["atmo_pm10"] = df_final["PM10"].apply(atmo_pm10)
df_final["atmo_no2"] = df_final["NO2"].apply(atmo_no2)

df_final["ATMO"] = df_final[["atmo_pm25", "atmo_pm10", "atmo_no2"]].max(axis=1)

In [5]:
def atmo_label(x):
    return {
        1: "Bon",
        2: "Moyen",
        3: "Dégradé",
        4: "Mauvais",
        5: "Très mauvais",
        6: "Extrêmement mauvais"
    }[x]

df_final["ATMO_label"] = df_final["ATMO"].apply(atmo_label)

In [6]:
df_final[["NO2", "PM10", "PM2.5", "ATMO"]].head()

    NO2  PM10  PM2.5  ATMO
0   7.0   4.8    1.0     1
1   1.7   3.7    2.9     1
2   9.5   2.5    1.2     1
3   5.1   7.1    6.5     1
4  27.7  11.7    9.3     1

In [7]:
df_final["ATMO"].value_counts()

ATMO
1    33622
2    19565
4     6980
3     5224
5      314
6       15
Name: count, dtype: int64

In [8]:
df_final

,date,code site,NO2,PM10,PM2.5,Latitude,Longitude,meteo_index,distance_meteo,station,temperature,Humidité,wind,rain,atmo_pm25,atmo_pm10,atmo_no2,ATMO,ATMO_label
0,2026-03-15 00:00:00,FR01011,7.0,4.8,1.0,49.119442,6.180833,64482,0.153349,AEROPORT METZ-NANCY-LORRAINE,18.2,63.0,5.7,0.0,1,1,1,1,Bon
1,2026-03-15 00:00:00,FR29439,1.7,3.7,2.9,45.481777,4.429667,10505,0.150109,ST ETIENNE-BOUTHEON,2.3,91.0,3.7,0.6,1,1,1,1,Bon
2,2026-03-15 00:00:00,FR24036,9.5,2.5,1.2,43.702076,7.286256,12534,0.093826,NICE,13.3,40.0,6.3,0.0,1,1,1,1,Bon
3,2026-03-15 00:00:00,FR24038,5.1,7.1,6.5,44.548650,6.067237,97742,0.442004,EMBRUN,3.6,49.0,1.6,0.0,1,1,1,1,Bon
4,2026-03-15 00:00:00,FR25036,27.7,11.7,9.3,49.442356,1.093789,39725,0.099707,ROUEN-BOOS,9.8,76.0,7.3,0.0,1,1,1,1,Bon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65715,2026-03-30 10:00:00,FR08614,6.1,5.5,2.4,43.834400,4.374400,98044,0.039025,NIMES-COURBESSAC,6.8,38.0,5.8,0.0,1,1,1,1,Bon
65716,2026-03-30 10:00:00,FR08016,3.1,11.2,2.9,43.591500,3.886810,96334,0.079352,MONTPELLIER-AEROPORT,12.8,29.0,13.7,0.0,1,1,1,1,Bon
65717,2026-03-30 10:00:00,FR18043,6.2,20.1,11.3,49.259552,2.474397,17854,0.251627,ROISSY,8.5,92.0,5.1,0.0,2,2,1,2,Moyen
65718,2026-03-30 10:00:00,FR07057,4.2,1.1,0.8,46.561974,3.340639,55214,0.399543,VICHY-CHARMEIL,9.8,78.0,3.9,0.0,1,1,1,1,Bon
65719,2026-03-30 10:00:00,FR82040,6.4,4.7,3.6,47.096720,5.496389,84418,0.086981,TAVAUX SA,-0.9,100.0,2.1,0.0,1,1,1,1,Bon

In [10]:
df_final.to_csv("data_final.csv", index=False)