# Nettoyage du dataset meteo

### Chargement du fichier

In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/PC/DATA/raw/synop_2026.csv", sep=";")
df

,lat,lon,geo_id_wmo,geo_id_wigos,name,reference_time,insert_time,validity_time,pmer,tend,...,hnuage1,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4
0,50.732500,1.599667,7002,0-20000-0-07002,BOULOGNE-SEM,2026-01-01T00:10:06Z,2026-01-01T00:02:31Z,2026-01-01T00:00:00Z,102010.0,-310.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50.514500,1.622833,7003,0-20000-0-07003,LE-TOUQUET,2026-01-01T00:10:06Z,2026-01-01T00:06:42Z,2026-01-01T00:00:00Z,102040.0,-320.0,...,690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50.136000,1.834000,7005,0-20000-0-07005,ABBEVILLE,2026-01-01T00:10:06Z,2026-01-01T00:02:29Z,2026-01-01T00:00:00Z,102110.0,-300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51.055833,2.339500,7010,0-20000-0-07010,DUNKERQUE,2026-01-01T00:10:06Z,2026-01-01T00:02:29Z,2026-01-01T00:00:00Z,101880.0,-330.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50.570000,3.097500,7015,0-20000-0-07015,LILLE-LESQUIN,2026-01-01T00:10:06Z,2026-01-01T00:02:29Z,2026-01-01T00:00:00Z,102000.0,-280.0,...,750.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132630,43.911333,4.902500,7563,0-20000-0-07563,AVIGNON,2026-03-29T22:10:06Z,2026-03-29T21:10:03Z,2026-03-29T21:00:00Z,102340.0,200.0,...,4260.0,3.0,NaN,4860.0,NaN,NaN,NaN,NaN,NaN,NaN
132631,43.576167,3.964667,7643,0-20000-0-07643,MONTPELLIER-AEROPORT,2026-03-29T22:10:06Z,2026-03-29T21:10:03Z,2026-03-29T21:00:00Z,102680.0,250.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132632,43.612833,5.108000,7648,0-20000-0-07648,SALON DE PROVENCE,2026-03-29T22:10:06Z,2026-03-29T21:10:03Z,2026-03-29T21:00:00Z,102170.0,230.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132633,-49.352333,70.243333,61998,0-20000-0-61998,KERGUELEN,2026-03-29T22:10:06Z,2026-03-29T21:16:37Z,2026-03-29T21:00:00Z,102480.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132634,-66.663167,140.001000,89642,0-20000-0-89642,DUMONT D'URVILLE,2026-03-29T22:10:06Z,2026-03-29T21:16:37Z,2026-03-29T21:00:00Z,99450.0,170.0,...,990.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Sélection des colonnes utiles

In [3]:
columns = [
    "validity_time",
    "name",
    "lat",
    "lon",
    "t",
    "u",
    "ff",
    "rr1"
]

df = df[columns]

### Renommer les colonnes pour une meilleures lisibilités et compréhension

In [4]:
df = df.rename(columns={
    "validity_time": "date",
    "name": "station",
    "t": "temperature",
    "u": "Humidité",
    "ff": "wind",
    "rr1": "rain"
})

### Conversion de date en datetime

In [5]:
df["date"] = pd.to_datetime(df["date"])

### Gestion des valeurs manquantes

In [6]:
df = df.dropna()

### Sauvegarde du dataset propre

In [7]:
df.to_csv("meteo_clean.csv", index=False)

In [8]:
df

,date,station,lat,lon,temperature,Humidité,wind,rain
0,2026-01-01 00:00:00+00:00,BOULOGNE-SEM,50.732500,1.599667,277.05,81.0,6.5,0.0
1,2026-01-01 00:00:00+00:00,LE-TOUQUET,50.514500,1.622833,278.35,72.0,4.6,0.0
2,2026-01-01 00:00:00+00:00,ABBEVILLE,50.136000,1.834000,275.85,89.0,1.3,0.0
3,2026-01-01 00:00:00+00:00,DUNKERQUE,51.055833,2.339500,277.75,79.0,7.5,0.0
4,2026-01-01 00:00:00+00:00,LILLE-LESQUIN,50.570000,3.097500,273.75,92.0,3.7,0.0
...,...,...,...,...,...,...,...,...
132628,2026-03-29 21:00:00+00:00,LANVEOC,48.279333,-4.439333,283.55,84.0,8.7,0.0
132629,2026-03-29 21:00:00+00:00,AVORD,47.052167,2.642167,277.75,68.0,2.8,0.0
132630,2026-03-29 21:00:00+00:00,AVIGNON,43.911333,4.902500,282.15,49.0,12.7,0.0
132631,2026-03-29 21:00:00+00:00,MONTPELLIER-AEROPORT,43.576167,3.964667,282.95,35.0,5.5,0.0
132632,2026-03-29 21:00:00+00:00,SALON DE PROVENCE,43.612833,5.108000,282.15,50.0,10.0,0.0

In [9]:
df.describe()

,lat,lon,temperature,Humidité,wind,rain
count,125554.000000,125554.000000,125554.000000,125554.000000,125554.000000,125554.000000
mean,37.236746,-2.627766,283.754589,80.518311,4.189538,0.134141
std,22.526797,43.203835,8.047765,15.340239,3.055407,0.722743
min,-49.352333,-176.194167,259.750000,1.000000,0.000000,-0.100000
25%,43.383167,-0.614333,278.950000,71.000000,2.000000,0.000000
50%,45.665000,2.339500,282.450000,84.000000,3.500000,0.000000
75%,48.279333,5.108000,286.050000,93.000000,5.700000,0.000000
max,51.055833,167.241167,310.250000,100.000000,32.700000,27.800000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 125554 entries, 0 to 132632
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   date         125554 non-null  datetime64[ns, UTC]
 1   station      125554 non-null  object
 2   lat          125554 non-null  float64
 3   lon          125554 non-null  float64
 4   temperature  125554 non-null  float64
 5   Humidité     125554 non-null  float64
 6   wind         125554 non-null  float64
 7   rain         125554 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(6), object(1)
memory usage: 8.6+ MB

##### Après vérification de  la cohérence statistique des données,  des anomalies ont été retrouvés: températures en Kelvin au lieu d'être en °C, lat et lon nous montre que les données vont au delà de la france et étant donnée que les données de pollution sont uniquement centré en france, on va centré ceux de météo sur France aussi. On  se rend compte aussi que la valeur minimal de rain est négatif, ce qui est physiquement impossible.

##### Alors, on va corriger ça

In [11]:
# 1. Température en °C
df["temperature"] = df["temperature"] - 273.15

# 2. Filtre géographique (France)
df = df[
    (df["lat"] >= 41) & (df["lat"] <= 51) &
    (df["lon"] >= -5) & (df["lon"] <= 9)
]

# 3. Corriger pluie
df["rain"] = df["rain"].clip(lower=0)

C:\Users\PC\AppData\Local\Temp\ipykernel_29096\1012213616.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["rain"] = df["rain"].clip(lower=0)

In [12]:
df.describe()

,lat,lon,temperature,Humidité,wind,rain
count,100191.000000,100191.000000,100191.000000,100191.000000,100191.000000,100191.000000
mean,46.454064,2.346520,7.799171,81.092364,4.023229,0.125800
std,2.276960,3.110967,4.835318,16.023250,2.903008,0.526942
min,41.918000,-4.664167,-13.400000,1.000000,0.000000,0.000000
25%,44.144500,0.110167,5.000000,72.000000,1.900000,0.000000
50%,46.705000,2.359833,8.300000,86.000000,3.400000,0.000000
75%,48.548000,4.902500,10.900000,94.000000,5.400000,0.000000
max,50.732500,8.922667,27.000000,100.000000,32.700000,25.700000

In [13]:
df.to_csv("meteo_clean.csv", index=False)

In [14]:
df

,date,station,lat,lon,temperature,Humidité,wind,rain
0,2026-01-01 00:00:00+00:00,BOULOGNE-SEM,50.732500,1.599667,3.9,81.0,6.5,0.0
1,2026-01-01 00:00:00+00:00,LE-TOUQUET,50.514500,1.622833,5.2,72.0,4.6,0.0
2,2026-01-01 00:00:00+00:00,ABBEVILLE,50.136000,1.834000,2.7,89.0,1.3,0.0
4,2026-01-01 00:00:00+00:00,LILLE-LESQUIN,50.570000,3.097500,0.6,92.0,3.7,0.0
5,2026-01-01 00:00:00+00:00,PTE DE LA HAGUE,49.725167,-1.939833,6.9,69.0,4.5,0.0
...,...,...,...,...,...,...,...,...
132628,2026-03-29 21:00:00+00:00,LANVEOC,48.279333,-4.439333,10.4,84.0,8.7,0.0
132629,2026-03-29 21:00:00+00:00,AVORD,47.052167,2.642167,4.6,68.0,2.8,0.0
132630,2026-03-29 21:00:00+00:00,AVIGNON,43.911333,4.902500,9.0,49.0,12.7,0.0
132631,2026-03-29 21:00:00+00:00,MONTPELLIER-AEROPORT,43.576167,3.964667,9.8,35.0,5.5,0.0
132632,2026-03-29 21:00:00+00:00,SALON DE PROVENCE,43.612833,5.108000,9.0,50.0,10.0,0.0